version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /frontend
    schedule:
      interval: weekly
    groups:
      frontend-docker:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend-docker:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"